services:
  app:
    build:
      target: dev
    volumes:
      - ./app:/app
      - /app/node_modules

  storybook:
    build:
      target: storybook
    volumes:
      - ./app:/app
      - /app/node_modules
    